FROM node:22-alpine

ENV NODE_ENV=development

WORKDIR /app

COPY package*.json ./
COPY prisma/ ./prisma/

RUN npm install
RUN npx prisma generate 

COPY . .

EXPOSE 3001
EXPOSE 5555

ENTRYPOINT ["npm", "run"]
CMD ["start:dev"]